# Internal logging level of the Log4j2 framework itself
status = warn

# --- APPENDER (Console) ---
appender.A1.type = Console
appender.A1.name = A1
appender.A1.layout.type = PatternLayout
appender.A1.layout.pattern = %-5p [BigDEC] %d{ISO8601} %c{1}: %m%n

# --- LOGGERS ---

# Logger for BigDEC
logger.bigdec.name = es.udc.gac.bigdec
logger.bigdec.level = WARN
logger.bigdec.appenderRef.A1.ref = A1

# Logger to silence Hadoop noise in Flink
logger.flink_hadoop.name = org.apache.flink.api.java.hadoop
logger.flink_hadoop.level = WARN
logger.flink_hadoop.appenderRef.A1.ref = A1

# Silence the harmless warning from Hadoop's native libraries
logger.hadoop_native.name = org.apache.hadoop.util.NativeCodeLoader
logger.hadoop_native.level = ERROR
logger.hadoop_native.appenderRef.A1.ref = A1

# Root logger to capture the rest of the events at a prudent level
rootLogger.level = INFO
rootLogger.appenderRef.A1.ref = A1
