# Internal logging level of the Log4j2 framework itself
status = warn

# --- Generic appender for Spark/Flink ---
appender.framework.type = Console
appender.framework.name = FRAMEWORK_OUT
appender.framework.layout.type = PatternLayout
appender.framework.layout.pattern = %-5p %d{ISO8601} %c{1}: %m%n

# --- Appender for BigDEC ---
appender.app.type = Console
appender.app.name = APP_OUT
appender.app.layout.type = PatternLayout
appender.app.layout.pattern = %-5p [BigDEC] %d{ISO8601} %c{1}: %m%n

# --- LOGGERS ---

# Logger for BigDEC
logger.bigdec.name = es.udc.gac
logger.bigdec.level = INFO
logger.bigdec.additivity = false
logger.bigdec.appenderRef.app.ref = APP_OUT

# Logger to silence Hadoop noise in Flink
logger.flink_hadoop.name = org.apache.flink.api.java.hadoop
logger.flink_hadoop.level = WARN
logger.flink_hadoop.additivity = false
logger.flink_hadoop.appenderRef.framework.ref = FRAMEWORK_OUT

# Silence the harmless warning from Hadoop's native libraries
logger.hadoop_native.name = org.apache.hadoop.util.NativeCodeLoader
logger.hadoop_native.level = ERROR
logger.hadoop_native.additivity = false
logger.hadoop_native.appenderRef.framework.ref = FRAMEWORK_OUT

# Root logger to capture the rest of the events at a prudent level
rootLogger.level = WARN
rootLogger.appenderRef.framework.ref = FRAMEWORK_OUT
